version: '3.8'

services:
  summoners-guide-overlay:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "3001:3001" # HMR port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ENABLE_MOCKS=true
      - MOCK_GAME_STATE=ChampSelect
      - MOCK_CHAMPION=Yasuo
      - MOCK_ROLE=mid
      - DEV_PORT=3000
      - DEV_HOST=0.0.0.0
    command: npm run dev
    stdin_open: true
    tty: true